frontend_nextjs/Components/select_students/StudentListAndFilters.js
=> inf scol now uses correct scrollbar

backend/app/models/participation.py
=> make Skill optional in participation

backend/app/models/user.py, backend/app/tests/test_routers/test_user_invites.py, backend/app/tests/test_routers/test_users.py, backend/app/tests/utils_for_tests/UserGenerator.py, frontend_nextjs/Components/settings/UserTr.js
=> make coach default & removed no role

backend/app/models/project.py, backend/app/routers/ddd.py, backend/app/tests/test_routers/test_projects.py, frontend_nextjs/pages/new-project.js, frontend_nextjs/pages/project/[project_id].js
=> remove goals attribute from Project

frontend_nextjs/Components/projects/RequiredSkillSelector.js, frontend_nextjs/Components/projects/SkillSelector.js
removed a dependency and forgot to remove some of its imports
=> Should fix current crashing

frontend_nextjs/Components/Auth.js
Reconnect websocket when connection is lost
=> Reconnect websocket

frontend_nextjs/Components/settings/QuestionTag.js
When the edited questiontag loses focus, its value goes back to the original one.
This pr solves that bug.
=> edit questiontag bugfix

frontend_nextjs/pages/login.js
this is useful for browsers that autocomplete password, this way the user doesn't need to press the login button but the browser can do it for you on autocomplete
=> make login & reset passwd a form

frontend_nextjs/Components/select_students/EmailBottomBar.js, frontend_nextjs/Components/select_students/StudentListAndFilters.js, frontend_nextjs/pages/select-students.js, frontend_nextjs/styles/filters.css
When the screen is to small in height to fit the filters, there is a scrollbar added to the filters. 
The student list is not messed up when scrolling the filters.
=> filters met scroll

frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/Components/settings/ManageUsers.js
due to unused imports, there were invalid paths in the application.
This pr removed the unused imports.
=> students to select students bugfix

frontend_nextjs/Components/email-students/DefaultEmail.js, frontend_nextjs/Components/settings/CreateEdition.js, frontend_nextjs/Components/settings/DefaultEmails.js, frontend_nextjs/Components/settings/EditionSettings.js, frontend_nextjs/Components/settings/SettingCards.js, frontend_nextjs/pages/_app.js, frontend_nextjs/styles/defaultEmail.css, frontend_nextjs/styles/emailStudents.css, frontend_nextjs/styles/login.css, frontend_nextjs/styles/settingcards.css
I tried some things out and in my opinion is a pop-up not necessary
=> Make default e-mail pop-up

backend/app/models/participation.py, backend/app/models/project.py, backend/app/routers/participations.py, backend/app/routers/projects.py, frontend_nextjs/Components/projects/AddStudentModal.js, frontend_nextjs/Components/projects/ParticipationCard.js, frontend_nextjs/Components/projects/ProjectCard.js, frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/package.json, frontend_nextjs/pages/project/[project_id].js, frontend_nextjs/utils/ApiClient.js
=> Implement websockets for participations

backend/app/models/student.py, backend/app/routers/students.py, frontend_nextjs/Components/students/DeletePopUpWindow.js, frontend_nextjs/Components/students/StudentDetails.js, frontend_nextjs/Components/students/StudentListAndFilters.js, frontend_nextjs/utils/ApiClient.js
=> Implement websocket on student delete

backend/app/routers/participations.py, frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/pages/project/[project_id].js
=> add websockets to details project

backend/app/routers/editions.py, frontend_nextjs/Components/students/StudentListAndFilters.js, frontend_nextjs/Components/students/StudentsFilters.js, frontend_nextjs/utils/ApiClient.js
=> Implement unmached student filter

frontend_nextjs/Components/settings/EditionSettings.js
=> edition edit now shows the name & description of the current edition

backend/app/routers/projects.py
=> added router to delete project

backend/app/routers/students.py, frontend_nextjs/Components/students/StudentListAndFilters.js, frontend_nextjs/utils/ApiClient.js
=> Fixed the websockets student refresh #481

backend/app/routers/editions.py, backend/app/routers/projects.py, backend/app/tests/test_routers/test_projects.py
=> coaches should see projects

frontend_nextjs/utils/ApiClient.js
=> uses localstorage to avoid not properly selecting the edition (year)

frontend_nextjs/cypress/integration/app.spec.js, frontend_nextjs/cypress/integration/login.spec.js, frontend_nextjs/cypress/integration/students.spec.js, frontend_nextjs/package.json
Updates the existing tests and Cypress itself.
Also adds tests for the students page.
=> Improve cypress tests

frontend_nextjs/Components/students/GeneralInfo.js
=> show email in student details

backend/app/utils/tallyhandler.py, frontend_nextjs/Components/students/GeneralInfo.js
emails were also diplayed in the list element (my bad), this fixes that
=> emails only displayed in details

frontend_nextjs/Components/settings/QuestionTag.js
Changing the visibility of question tags did not work always before this pr.
This pr solves that issue
=> questiontags bugfix

frontend_nextjs/Components/projects/AddStudentModal.js
=> reset the add student modal for creating a participation

backend/app/database.py, backend/app/exceptions/questiontag_exceptions.py, backend/app/models/edition.py, backend/app/models/project.py, backend/app/models/question_tag.py, backend/app/models/student.py, backend/app/models/suggestion.py, backend/app/models/user.py, backend/app/routers/auth.py, backend/app/routers/reset_password.py, backend/app/routers/sendemails.py, backend/app/routers/tally.py, backend/app/routers/users.py, backend/app/tests/test_utils/test_key_generators.py, backend/app/utils/mailsender.py, backend/app/utils/websocketmanager.py, frontend_nextjs/Components/Auth.js, frontend_nextjs/Components/projects/AddStudentModal.js, frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/Components/projects/RequiredSkillSelector.js, frontend_nextjs/Components/students/SendCustomEmailPopUp.js, frontend_nextjs/Components/students/SuggestionPopUpWindow.js, frontend_nextjs/pages/new-project.js, frontend_nextjs/pages/project/[project_id].js, frontend_nextjs/utils/string.js, info/user_manual.md
Sorry i had 30 minutes to fill.
=> Clean documentation

frontend_nextjs/Components/students/StudentsFilters.js
=> reset filters

frontend_nextjs/Components/settings/ManageUsers.js
=> filters combined with search

backend/app/tests/test_base.py, backend/app/tests/utils_for_tests/DataGenerator.py, backend/app/tests/utils_for_tests/EditionGenerator.py, backend/app/tests/utils_for_tests/QuestionAnswerGenerator.py, backend/app/tests/utils_for_tests/SkillGenerator.py, backend/app/tests/utils_for_tests/StudentGenerator.py, backend/app/tests/utils_for_tests/UserGenerator.py
This pull request adds docstrings to the testbase and replaces deprecated type annotations.
=> document test_base

backend/app/routers/editions.py, backend/app/routers/participations.py, frontend_nextjs/Components/projects/ConflictCard.js, frontend_nextjs/Components/projects/ConflictsPopUpWindow.js, frontend_nextjs/Components/projects/ParticipationCard.js, frontend_nextjs/Components/projects/ProjectCard.js, frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/styles/projects.css, frontend_nextjs/utils/ApiClient.js
This pr makes the screen for solving conflicts. When the conflicts button is clicked, a pop up window opens and shows the conflicts.
=> conflicts solving screen

frontend_nextjs/Components/students/SearchSortBar.js, frontend_nextjs/styles/globals.css
=> Automatic search for students

frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/Components/students/StudentListAndFilters.js
=> clear selected on filters change

frontend_nextjs/Components/students/StudentListAndFilters.js
=> delete student doesn't dissapear

backend/app/routers/editions.py
=> Deleted the endpoint

frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/Components/students/StudentListAndFilters.js, frontend_nextjs/styles/students.css
This pr solves the issue that the email bottom bar was not visible anymore.
It also fixes some margins of the student-list, -filters, -projects and -details.
=> fix email bottom bar and some layout fixes

frontend_nextjs/Components/projects/ProjectCard.js, frontend_nextjs/Components/projects/ProjectsList.js
=> websockets required skills in projects

frontend_nextjs/Components/projects/SkillSelector.js
=> make skill search case-insensitive

frontend_nextjs/Components/email-students/DefaultEmail.js, frontend_nextjs/Components/email-students/SendEmailsPopUpWindow.js
This pr does a cleanup and adds documentation to the 'email students' folder
=> cleanup and documentation email students

frontend_nextjs/Components/projects/AddStudentModal.js, frontend_nextjs/Components/projects/ConflictCard.js, frontend_nextjs/Components/projects/ConflictsPopUpWindow.js, frontend_nextjs/Components/projects/ParticipationCard.js, frontend_nextjs/Components/projects/ProjectCard.js, frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/Components/projects/RequiredSkillSelector.js, frontend_nextjs/Components/projects/SkillCard.js, frontend_nextjs/Components/projects/SkillSelector.js, frontend_nextjs/pages/new-project.js, frontend_nextjs/pages/project/[project_id].js, frontend_nextjs/pages/projects.js, frontend_nextjs/utils/skillselector.js
This pr adds more documentation to the projects tab and the 'new project' page.
=> documentation projects

frontend_nextjs/pages/project/[project_id].js
makes projectid (project details) responsive.
=> make project_id responsive

frontend_nextjs/Components/settings/ChangeEmail.js, frontend_nextjs/Components/settings/ChangeName.js, frontend_nextjs/Components/settings/ChangePassword.js, frontend_nextjs/Components/settings/ChangeTheme.js, frontend_nextjs/Components/settings/CreateEdition.js, frontend_nextjs/Components/settings/EditionSettings.js, frontend_nextjs/Components/settings/ManageUsers.js, frontend_nextjs/Components/settings/QuestionTag.js, frontend_nextjs/Components/settings/QuestionTags.js, frontend_nextjs/Components/settings/SettingCards.js, frontend_nextjs/Components/settings/UserTr.js, frontend_nextjs/pages/settings.js
This pr adds more documentation to the settings tab code.
=> settings documentation

frontend_nextjs/pages/api/auth/[...nextauth].js, frontend_nextjs/pages/invites/[invitekey].js, frontend_nextjs/pages/login.js, frontend_nextjs/pages/resetpassword/[resetkey].js, frontend_nextjs/pages/settings.js
This pr adds documentation to various pages.
=> pages documentation

frontend_nextjs/Components/NavHeader.js
=> remove localstorage `api_year` on logout

frontend_nextjs/Components/settings/EditionSettings.js, frontend_nextjs/Components/settings/QuestionTag.js, frontend_nextjs/Components/settings/QuestionTags.js
This pr adds toast messages when question tags are saved, edited or deleted.
During this pr I found a new bug #591 , which is not fixed yet. So this is a known bug.
This pr closes #587.
=> toast messages question tags

frontend_nextjs/Components/Auth.js, frontend_nextjs/Components/ErrorPage.js, frontend_nextjs/Components/Hint.js, frontend_nextjs/Components/LoadingPage.js, frontend_nextjs/Components/Message.js, frontend_nextjs/Components/NavHeader.js
This pr adds more documentation to various component files
=> documentation components

backend/app/models/question_answer.py, backend/app/routers/ddd.py, backend/app/routers/editions.py, backend/app/routers/students.py, backend/app/tests/utils_for_tests/QuestionAnswerGenerator.py, backend/app/utils/tallyhandler.py
=> Extract skills from tally form

backend/app/routers/editions.py
=> Deleting question tags does not work properly

frontend_nextjs/Components/projects/RequiredSkillSelector.js, frontend_nextjs/pages/new-project.js, frontend_nextjs/pages/project/[project_id].js, frontend_nextjs/styles/globals.css, frontend_nextjs/styles/projectDetails.css, frontend_nextjs/styles/projects.css, frontend_nextjs/utils/inputchecker.js
fixed small layout issues
fixed error messages
=> Project details and new project layout fix

frontend_nextjs/Components/projects/ConflictsPopUpWindow.js, frontend_nextjs/public/assets/left.svg, frontend_nextjs/public/assets/right.svg, frontend_nextjs/styles/projects.css
changed page numbering to allow more participationscards on the modal screen
=> changed page numbering

frontend_nextjs/Components/projects/ProjectCard.js, frontend_nextjs/styles/globals.css
=> make primary and secondary bold

frontend_nextjs/Components/projects/ParticipationCard.js, frontend_nextjs/Components/projects/ProjectCard.js, frontend_nextjs/Components/projects/RequiredSkillSelector.js, frontend_nextjs/utils/ApiClient.js
=> removed logs

frontend_nextjs/Components/projects/ConflictCard.js, frontend_nextjs/Components/projects/ConflictsPopUpWindow.js, frontend_nextjs/Components/projects/ProjectsList.js, frontend_nextjs/Components/students/SearchBar.js, frontend_nextjs/Components/students/SearchSortBar.js, frontend_nextjs/Components/students/StudentListAndFilters.js, frontend_nextjs/styles/colors.css, frontend_nextjs/styles/projects.css, frontend_nextjs/styles/studentListelement.css, frontend_nextjs/styles/students.css
This pr makes the searchbars in projects and students the same, it also does some small layout fixes.
It makes the background of the conflicts button darker.
It makes an message for the conflicts pup up window in case there are no conflicts.
=> searchbar projects and students the same

frontend_nextjs/styles/colors.css, frontend_nextjs/styles/globals.css
=> fix notifications bug + solved unresolved reference

frontend_nextjs/Components/students/StudentDetails.js
Coaches were authorized to make decisions before this pr, this pr solves this issue.
=> coaches are not permitted to make decisions

frontend_nextjs/styles/manageusers.css
Changed the width of button in manageusers
=> changed width in css
